#!/usr/bin/env node
// Reads index.html and regenerates README.md with current agent list + progress.
// Run directly: node scripts/generate-readme.js
// Triggered automatically by .git/hooks/pre-commit on every commit.

const fs   = require("fs");
const path = require("path");

const root      = path.resolve(__dirname, "..");
const htmlPath  = path.join(root, "index.html");
const readmePath = path.join(root, "README.md");

const html = fs.readFileSync(htmlPath, "utf8");

// Extract data-offset from the agents-grid div
const offsetMatch = html.match(/id="agents-grid"[^>]*data-offset="(\d+)"/);
const offset = offsetMatch ? parseInt(offsetMatch[1], 10) : 0;

// Extract every card inside the agents-grid section
// Strategy: slice the HTML between id="agents-grid" and the next <!-- comment
const gridStart = html.indexOf('id="agents-grid"');
const gridEnd   = html.indexOf("<!-- TTTT -->", gridStart);
const gridHtml  = html.slice(gridStart, gridEnd);

const cardRegex = /<div class="card-tag">#(\d+)\s*·\s*([^<]+)<\/div>\s*<h3>([^<]+)<\/h3>[\s\S]*?href="([^"]+)"/g;
const agents = [];
let m;
while ((m = cardRegex.exec(gridHtml)) !== null) {
  agents.push({
    num:      parseInt(m[1], 10),
    category: m[2].trim(),
    name:     m[3].trim(),
    url:      m[4].trim(),
  });
}
agents.sort((a, b) => a.num - b.num);

const cardCount = agents.length;
const total     = cardCount + offset;
const pct       = Math.round((total / 100) * 100);
const filled    = Math.round(total / 2);   // 50-char bar
const bar       = "█".repeat(filled) + "░".repeat(50 - filled);

const categoryEmoji = {
  "AI Dev":           "🤖",
  "Career":           "💼",
  "Study & CS":       "📚",
  "Mom's English":    "🇻🇳",
  "Sis English":      "🗣️",
  "Games & Fun":      "🎮",
  "Art & Creative":   "🎨",
  "Vietnamese Family":"🍜",
  "Fun & Learning":   "🌟",
};

function emoji(cat) {
  for (const [k, v] of Object.entries(categoryEmoji)) {
    if (cat.includes(k)) return v;
  }
  return "✨";
}

const rows = agents.map(a =>
  `| #${String(a.num).padStart(2, "0")} | ${emoji(a.category)} ${a.category} | [${a.name}](${a.url}) |`
).join("\n");

const readme = `# Han Han Nguyen — 100 AI Agents 🤖

> Building 100 AI-powered mini web-apps, one agent at a time.

## Progress

\`\`\`
${bar}  ${total} / 100
\`\`\`

**${total} / 100 agents built** · ${pct}% complete

🌐 [Live Portfolio](https://hhanng.github.io)

---

## Agent List

| # | Category | Agent |
|---|----------|-------|
${rows}

---

*README auto-generated by \`scripts/generate-readme.js\` — do not edit by hand.*
*Last updated: ${new Date().toISOString().split("T")[0]}*
`;

fs.writeFileSync(readmePath, readme, "utf8");
console.log(`README.md updated — ${total}/100 agents (${cardCount} cards + ${offset} offset)`);
